export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const SET_AUTOIN = 'SET_AUTOIN';
export const SET_AUTOIN_FAIL = 'SET_AUTOIN_FAIL';
export const SET_AUTOIN_LOADING = 'SET_AUTOIN_LOADING';

export const RTC_NEW_QUEUE = 'RTC_NEW_QUEUE';
export const RTC_NEW_INTERACTION = 'RTC_NEW_INTERACTION';

export const GET_INTERACTION = 'GET_INTERACTION';
export const GET_INTERACTION_FAIL = 'GET_INTERACTION_FAIL';
export const UPDATE_INTERACTION = 'UPDATE_INTERACTION';
export const INTERACTION_LOADED = 'INTERACTION_LOADED';

export const SENDING_INTERACTION = 'SENDING_INTERACTION';
export const SENT_SUCCESS = 'SENT_SUCCESS';
export const SENT_FAIL = 'SENT_FAIL';

export const RESET_CHAT_COUNT = 'RESET_CHAT_COUNT';
